### ISSUE TITLE
installing package

### ISSUE THREAD

**Issue by ghost** [MobilePhoneESSnetBigData/mobvis#1]
Hi
`> install_github("MobilePhoneESSnetBigData/mobvis")`

Executing the above command, the following error occurs:

`Error in grid.newpage() : could not open file 'output/r.png'
Error: unable to load R code in package ‘mobvis’
Execution halted
ERROR: lazy loading failed for package ‘mobvis’
`

**Comment by mtennekes** [comment]
Thanks for letting me know. It should be fixed, so installation should work now. Let me know if not.
